// Generates TypeScript types and CSP-safe validators from schema/protocol.schema.json (DEC-006).
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { compile } from "json-schema-to-typescript";

const root = new URL("../", import.meta.url);
const schema = JSON.parse(readFileSync(new URL("schema/protocol.schema.json", root), "utf8"));
const out = new URL("src/generated/", root);
mkdirSync(out, { recursive: true });
const banner =
  "// GENERATED by scripts/generate.mjs from schema/protocol.schema.json. Do not edit.\n";

// Types: compile a wrapper that references every top-level definition so each gets a named type.
const wrapper = {
  ...schema,
  title: "ProtocolRoot",
  type: "object",
  properties: Object.fromEntries(
    Object.keys(schema.$defs).map((k) => [k, { $ref: `#/$defs/${k}` }]),
  ),
  additionalProperties: false,
};
const ts = await compile(wrapper, "ProtocolRoot", {
  bannerComment: "",
  additionalProperties: false,
  unreachableDefinitions: false,
  style: { semi: true, singleQuote: false },
});
writeFileSync(new URL("types.ts", out), banner + ts);

// Validators: Ajv standalone code has no eval at runtime, so it works under the MV3 CSP.
const ajv = new Ajv2020({ code: { source: true, esm: true }, strict: false });
ajv.addSchema(schema);
const id = schema.$id;
const code = standaloneCode(ajv, {
  validateClientMessage: `${id}#/$defs/ClientMessage`,
  validateServerMessage: `${id}#/$defs/ServerMessage`,
  validateRoomTicket: `${id}#/$defs/RoomTicket`,
});
// Inline Ajv's one runtime helper so the output has no require() and no runtime dependency.
const inlined = code.replaceAll(
  'require("ajv/dist/runtime/ucs2length").default',
  "((s) => [...s].length)",
);
if (inlined.includes("require(")) throw new Error("validators.js still needs a runtime require");
writeFileSync(new URL("validators.js", out), `${banner}// @ts-nocheck\n${inlined}`);
writeFileSync(
  new URL("validators.d.ts", out),
  `${banner}type Validator = ((data: unknown) => boolean) & { errors?: { instancePath: string; message?: string }[] | null };
export declare const validateClientMessage: Validator;
export declare const validateServerMessage: Validator;
export declare const validateRoomTicket: Validator;
`,
);
console.log("protocol: generated types.ts and validators.js");
